### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by Fyoncle** [The-Architects727/BetterEndCitiesBetterEnd#1]

**Comment by Hi-ImKyle** [comment]
Doesn't seem to have an effect on 1.21, perhaps the file structure for replacing vanilla structures has changed for datapacks.

**Comment by Fyoncle** [comment]
> Doesn't seem to have an effect on 1.21, perhaps the file structure for replacing vanilla structures has changed for datapacks.

Yeah that's why im asking for a port.

**Comment by Hi-ImKyle** [comment]
Maybe you are confused. Just because I posted a comment, doesn't mean you have to respond. I am well aware you are asking for a port, it's the point in the issue you made. The reason I commented was to further the issue, maybe suggest why it might not be working.

That being said, I have since got it working but it's not a consistent fix. For what ever reason the datapack version doesn't change the structures.

**Comment by The-Architects727** [comment]
There was a slight change in the form of the datapack structure. I am working on the fix now.

**Comment by Fyoncle** [comment]
> There was a slight change in the form of the datapack structure. I am working on the fix now.

Perfect!

**Comment by The-Architects727** [comment]
I have completed the update, and both the mods, and the datapacks are updated on both modrinth and curseforge. If i missed anything, please let me know.
